-- Script de creacion de base de datos ACTIVO_FIJO_DW
-- Creado: 25/08/2024

CREATE DATABASE ACTIVO_FIJO_DW
GO

USE ACTIVO_FIJO_DW
GO

CREATE TABLE DIM_FECHA(
	FECHA_KEY VARCHAR(10) NOT NULL,
	FECHA_COMPLETA DATETIME NOT NULL,
	CUARTO SMALLINT NOT NULL DEFAULT(0)
	DIA_DEL_MES TINYINT NOT NULL DEFAULT(0),
	MES_CALENDARIO TINYINT NOT NULL DEFAULT(0),
	ANIO_CALENDARIO SMALLINT NOT NULL DEFAULT(0)
)
GO

CREATE TABLE DIM_PRODUCTO(
	PRODUCTO_KEY BIGINT IDENTITY(1,1) PRIMARY KEY,
	PRODUCTO_ID BIGINT NOT NULL,
	TIPO_PRODUCTO VARCHAR(50) NOT NULL,
	ESTADO_PRODUCTO VARCHAR(50) NOT NULL,
	DESCRIPCION_PRODUCTO VARCHAR(200) NOT NULL,
	TASA_DEPRECIACION FLOAT DEFAULT (0) NOT NULL
)
GO

CREATE TABLE DIM_DETALLE_PRODUCTO(
	DETALLE_PROD_KEY BIGINT IDENTITY(1,1) PRIMARY KEY,
	DETALLE_PROD_ID BIGINT NOT NULL,
	VALOR_ANTERIOR FLOAT DEFAULT(0) NOT NULL,
	VALOR_ACTUAL FLOAT DEFAULT(0) NOT NULL,
	VALOR_DEPRECIADO FLOAT DEFAULT(0) NOT NULL
)
GO

CREATE TABLE DIM_UBICACION(
	UBICACION_KEY BIGINT IDENTITY(1,1) PRIMARY KEY,
	UBICACION_ID BIGINT NOT NULL,
	DIRECCION_COMPLETA VARCHAR(200) NOT NULL,
	CALLE VARCHAR(50) NOT NULL,
	AVENIDA VARCHAR(50) NOT NULL,
	NUMERO_DE_PROPIEDAD TINYINT DEFAULT(0) NOT NULL,
	MUNICIPIO VARCHAR(70) NOT NULL,	
	DEPARTAMENTO VARCHAR(70) NOT NULL,
	PAIS VARCHAR(70) NOT NULL
)
GO

CREATE TABLE FACT_ACTIVO_FIJO(
	FECHA_KEY BIGINT NOT NULL FOREIGN KEY REFERENCES DIM_FECHA(FECHA_KEY),
	UBICACION_KEY BIGINT NOT NULL FOREIGN KEY REFERENCES DIM_UBICACION(UBICACION_KEY),
	PRODUCTO_KEY BIGINT NOT NULL FOREIGN KEY REFERENCES DIM_PRODUCTO(PRODUCTO_KEY),
	DETALLE_PROD_KEY BIGINT NOT NULL FOREIGN KEY REFERENCES DIM_DETALLE_PRODUCTO(DETALLE_PROD_KEY),
	MONTO_UNITARIO FLOAT DEFAULT(0) NOT NULL,
	MES_DE_COMPRA INT NOT NULL,
	ANIO_DE_COMPRA INT NOT NULL
)
GO
