-- Script de creacion de base de datos ACTIVO_FIJO_DW
-- Creado: 25/08/2024

/*CREATE DATABASE ACTIVO_FIJO_DW
GO

USE ACTIVO_FIJO_DW
GO*/

CREATE TABLE DIM_FECHA(
	FECHA_KEY INT PRIMARY KEY,
	FECHA_COMPLETA DATETIME NOT NULL,
	CUARTO SMALLINT NOT NULL DEFAULT(0),
	ANIO_FISCAL INT NOT NULL DEFAULT(0),
	ANIO_CALENDARIO INT NOT NULL DEFAULT(0),
	MES_CALENDARIO TINYINT NOT NULL DEFAULT(0),
	DIA_DEL_MES TINYINT NOT NULL DEFAULT(0),
	NOMBRE_DIA	VARCHAR(15) NOT NULL DEFAULT 'N/A',
	DIA_ABREV	VARCHAR(3) NOT NULL DEFAULT 'N/A'
)
GO

CREATE TABLE DIM_PRODUCTO(
	PRODUCTO_KEY BIGINT IDENTITY(1,1) PRIMARY KEY,
	PRODUCTO_ID BIGINT NOT NULL,
	TIPO_PRODUCTO VARCHAR(50) NOT NULL DEFAULT 'N/A',
	ESTADO_PRODUCTO VARCHAR(50) NOT NULL DEFAULT 'N/A',
	TIPO_DE_MONEDA VARCHAR(15) NOT NULL DEFAULT 'N/A',
	METODO_DEPRECIACION VARCHAR(50) NOT NULL DEFAULT 'N/A',
	TASA_DEPRECIACION DECIMAL(25,5) NOT NULL DEFAULT (0)
)
GO

CREATE TABLE DIM_VENDEDOR(
	VENDEDOR_KEY BIGINT IDENTITY(1,1) PRIMARY KEY,
	VENDEDOR_ID BIGINT NOT NULL,
	NOMBRE_VENDEDOR VARCHAR(100) NOT NULL DEFAULT 'N/A',
	RANGO INT NOT NULL DEFAULT(0),
	SITIO_WEB VARCHAR(100) NOT NULL DEFAULT 'N/A',
	EMAIL VARCHAR(100) NOT NULL DEFAULT 'N/A',
	TELEFONO VARCHAR(30) NOT NULL DEFAULT 'N/A',
	UBICACION VARCHAR(100) NOT NULL DEFAULT 'N/A'
)
GO

CREATE TABLE FACT_ACTIVO_FIJO(
	FECHA_KEY INT NOT NULL FOREIGN KEY REFERENCES DIM_FECHA(FECHA_KEY),
	--UBICACION_KEY BIGINT NOT NULL FOREIGN KEY REFERENCES DIM_UBICACION(UBICACION_KEY),
	PRODUCTO_KEY BIGINT NOT NULL FOREIGN KEY REFERENCES DIM_PRODUCTO(PRODUCTO_KEY),
	VENDEDOR_KEY BIGINT NOT NULL FOREIGN KEY REFERENCES DIM_VENDEDOR(VENDEDOR_KEY),
	--DETALLE_PROD_KEY BIGINT NOT NULL FOREIGN KEY REFERENCES DIM_DETALLE_PRODUCTO(DETALLE_PROD_KEY),
	VALOR_DE_COMPRA DECIMAL(25,2) NOT NULL DEFAULT(0),
	VALOR_ANTERIOR DECIMAL(25,2) NOT NULL DEFAULT(0),
	VALOR_ACTUAL 	DECIMAL(25,2) NOT NULL DEFAULT(0),
	VALOR_DEPRECIADO DECIMAL(25,2) NOT NULL DEFAULT(0),
	VALOR_RECUPERADO DECIMAL(25,2) NOT NULL DEFAULT(0),
	MES_DE_COMPRA INT NOT NULL,
	ANIO_DE_COMPRA INT NOT NULL
)
GO
